name: BOT AI Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: Run review
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run review
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-pr-id: ${{ github.event.number }}
          dev-lang: Javascript
          openai-max-tokens: 4096