name: GlobantBot Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: Run review
    steps:
      - uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-pr-id: ${{ github.event.number }}
          dev-lang: Javascript
          openai-max-tokens: 4096